CREATE TABLE IF NOT EXISTS branded_food (
    fdc_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    brand_owner VARCHAR(255) NULL,
    brand_name VARCHAR(255) NULL,
    subbrand_name VARCHAR(255) NULL,
    gtin_upc VARCHAR(50) NULL,
    ingredients MEDIUMTEXT NULL,
    not_a_significant_source_of MEDIUMTEXT NULL,
    serving_size DECIMAL(12,4) NULL,
    serving_size_unit VARCHAR(50) NULL,
    household_serving_fulltext VARCHAR(255) NULL,
    branded_food_category VARCHAR(255) NULL,
    data_source VARCHAR(100) NULL,
    package_weight VARCHAR(255) NULL,
    modified_date DATE NULL,
    available_date DATE NULL,
    market_country VARCHAR(100) NULL,
    discontinued_date DATE NULL,
    preparation_state_code VARCHAR(100) NULL,
    trade_channel VARCHAR(255) NULL,
    short_description TEXT NULL,
    INDEX idx_brand_owner (brand_owner),
    INDEX idx_brand_name (brand_name),
    INDEX idx_gtin_upc (gtin_upc),
    INDEX idx_branded_food_category (branded_food_category),
    FULLTEXT INDEX ft_ingredients (ingredients)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
